---

- hosts: ambari
  sudo: True
  tasks:
    - name: Adding Repos
      shell: wget -nv http://public-repo-1.hortonworks.com/ambari/ubuntu14/2.x/updates/2.4.2.0/ambari.list -O /etc/apt/sources.list.d/ambari.list -O /etc/apt/sources.list.d/ambari.list

    - apt_key: keyserver=keyserver.ubuntu.com id=B9733A7A07513CAD

    - apt: name=ambari-server update_cache=yes state=present

    - shell: ambari-server setup -s

    - action: shell nohup ambari-server start
      async: 1000000
      poll: 0

    - name: Copy private key to local machine
      fetch: src=/home/ambari/.ssh/id_rsa dest=/tmp/fetched/amabri/private_key flat=yes
